version: "3"
services:
  app:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ./config.json:/app/config/production.json
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db
    environment:
    # if you want pretty colors in your docker logs:
    - FORCE_COLOR=1
  db:
    image: mariadb/server:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: "npm"
      MARIADB_ROOT_HOST: "%"
      MARIADB_DATABASE: "npm"
      MARIADB_USER: "npm"
      MARIADB_PASSWORD: "npm"
    volumes:
      - ./data/mysql:/var/lib/mysql